# baseURL
# @baseURL = https://gate.mamnonhoalu.online/api
@baseURL = https://gate.mamnonhoalu.online/api

@Authorization = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjA0LCJjYXNoIjowLCJpc1ZlcmlmeSI6dHJ1ZSwibmFtZSI6bnVsbCwicGhvbmVOdW1iZXIiOiIrODQzMjc0NzYzODEiLCJhZGRyZXNzIjpudWxsLCJyb2xlIjoiVXNlciIsInBvaW50IjowLCJjcmVhdGVBdCI6IjIwMjMtMDktMTBUMDQ6NDM6NTMuMzU4WiIsImlhdCI6MTY5NDMyMzQ0NiwiZXhwIjoxNjk0NDA5ODQ2fQ.OZM0xV9oWxlpSMs9CPySjkHkvuqTKiniNAFpch712rw

#-----------------------------------CATEGORY

# Get all categories
GET  {{ baseURL }}/categories
Content-Type: application/json
###

# # Get detail category by slug category
# GET  {{ baseURL }}/category/xe-dia-hinh
# Content-Type: application/json
# ###

# # Create category
# POST {{ baseURL }}/category
# Content-Type: application/json

# {
#     "name": "Xe thể thao",
#     "slug": "xe-the-thao"
# }

# ###
# # Update category by slug
# PUT {{ baseURL }}/category/xe-the-thao
# Content-Type: application/json

# {
#     "name": "Xe thể thao 1",
#     "slug": "xe-the-thao-1"
# }

# ###
# # Delete category by slug
# DELETE {{ baseURL }}/category/xe-the-thao-1
# Content-Type: application/json
# ###

#-----------------------------------SUBCATEGORY

# Get all subCategories by slug category
GET  {{ baseURL }}/sub-categories/xe-dia-hinh
Content-Type: application/json
###

# # Get detail subCategory by slug subCategory
# GET {{ baseURL }}/sub-category/trek-bikes
# Content-Type: application/json
# ###

#-----------------------------------COLOR
GET  {{ baseURL }}/colors
Content-Type: application/json
###

# GET  {{ baseURL }}/color/%23ffffff
# Content-Type: application/json
# ###

#-----------------------------------SIZE
GET  {{ baseURL }}/sizes
Content-Type: application/json
###

# GET  {{ baseURL }}/size/m
# Content-Type: application/json
# ###

#-----------------------------------PRODUCT

# Get all products by filter
GET {{ baseURL }}/products?category=%5B%22xe-the-thao%22%2C%20%22xe-dia-hinh%22%2C%20%22xe-cu%22%5D&color=%5B%5D&fromPrice=0&toPrice=20000000
Content-Type: application/json
###

# Get products by slug category
GET {{ baseURL }}/products/category/xe-the-thao
Content-Type: application/json
###

# Get products by slug subcategory of slug category
GET {{ baseURL }}/products/xe-the-thao/bmc-switzerland
Content-Type: application/json
###

# Get products related by id
GET {{ baseURL }}/products/related?id=51
Content-Type: application/json
###

# Get all product by name (search live)
GET {{ baseURL }}/products/search?name=An%20do
Content-Type: application/json
###

# Get detail product by slug product
GET {{ baseURL }}/product/Xe-dap-the-thao-nhap-khau-tu-Dan-Mach-ma-7B3TKRLQPM

# ###
# # Create product
# POST {{ baseURL }}/product
# Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

# ------WebKitFormBoundary7MA4YWxkTrZu0gW
# Content-Disposition: form-data; name="files"; filename="nodejs.png"
# Content-Type: image/png

# > ./nodejs.png

# ------WebKitFormBoundary7MA4YWxkTrZu0gW
# Content-Disposition: form-data; name="name"

# xe dap abcd

# ------WebKitFormBoundary7MA4YWxkTrZu0gW
# Content-Disposition: form-data; name="slug"

# mtb-gammax-26-kunfeng-1-0-21s-2020

# ------WebKitFormBoundary7MA4YWxkTrZu0gW
# Content-Disposition: form-data; name="price"

# 2600000

# ------WebKitFormBoundary7MA4YWxkTrZu0gW
# Content-Disposition: form-data; name="discount"

# 40

# ------WebKitFormBoundary7MA4YWxkTrZu0gW
# Content-Disposition: form-data; name="size"

# ["s", "l"]

# ------WebKitFormBoundary7MA4YWxkTrZu0gW
# Content-Disposition: form-data; name="color"

# ["#ff0000", "#ffffff"]

# ------WebKitFormBoundary7MA4YWxkTrZu0gW
# Content-Disposition: form-data; name="sold"

# 2500

# ------WebKitFormBoundary7MA4YWxkTrZu0gW
# Content-Disposition: form-data; name="inventory"

# 400

# ------WebKitFormBoundary7MA4YWxkTrZu0gW
# Content-Disposition: form-data; name="detail"

# Xe đạp địa hình sở hữu thiết kế khỏe khoắn, đường nét mạnh mẽ với khung sườn nhỏ gọn kết hợp cùng logo cách điệu đẹp mắt, là phương tiện phù hợp để bạn dùng khi leo núi, đi phượt, vượt địa hình hay đơn giản là dùng khi tập thể thao hằng ngày. Mẫu xe có nhiều phiên bản màu (còn hàng tùy theo khu vực và thời điểm). Bài viết sử dụng phiên bản màu xám để minh họa.

# ------WebKitFormBoundary7MA4YWxkTrZu0gW
# Content-Disposition: form-data; name="categoryId"

# 1
# ------WebKitFormBoundary7MA4YWxkTrZu0gW--

# ###
# # Update product
# PUT {{ baseURL }}/product/mtb-gammax-26-kunfeng-1-0-21s-2020
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="files"; filename="test-upload.jpg"
Content-Type: image/jpeg

@ ./bicycle.jpg

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="name"

Xe Đạp Địa Hình Superme

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="slug"

xe-dap-dia-hinh-superme

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="price"

5000000

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="discount"

40

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="size"

["s", "l"]

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="color"

["#ff0000", "#ffffff"]

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="sold"

2500

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="inventory"

400

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="detail"

Xe đạp địa hình sở hữu thiết kế khỏe khoắn, đường nét mạnh mẽ với khung sườn nhỏ gọn kết hợp cùng logo cách điệu đẹp mắt, là phương tiện phù hợp để bạn dùng khi leo núi, đi phượt, vượt địa hình hay đơn giản là dùng khi tập thể thao hằng ngày. Mẫu xe có nhiều phiên bản màu (còn hàng tùy theo khu vực và thời điểm). Bài viết sử dụng phiên bản màu xám để minh họa.

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="categoryId"

1
------WebKitFormBoundary7MA4YWxkTrZu0gW--
###