# baseURL
@baseURL = https://gate.mamnonhoalu.online/api
@Authorization = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiY2FzaCI6MCwiaXNWZXJpZnkiOnRydWUsIm5hbWUiOm51bGwsInBob25lTnVtYmVyIjoiMDkzMzY2MzI0MCIsImFkZHJlc3MiOm51bGwsInJvbGUiOiJuZWtveWFzaGkiLCJwb2ludCI6MCwiY3JlYXRlQXQiOiIyMDIzLTA5LTEzVDE5OjA0OjA0LjAzNVoiLCJpYXQiOjE2OTQ2MzI2NjksImV4cCI6MTY5NDcxOTA2OX0.xCzOEfBVSCrrpl_5Oxvq8jAcd4bWZZ3bDb59rIrWmfU", "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicGhvbmVOdW1iZXIiOiIwOTMzNjYzMjQwIiwicm9sZSI6Im5la295YXNoaSIsImlzVmVyaWZ5Ijp0cnVlLCJpYXQiOjE2OTQ2MzI2NjksImV4cCI6MTY5NzIyNDY2OX0.ooaWKVg8AGFBAaZhAugAQWL3uXcnTzxPpmH9EXPDwLU

###
# Fetch Info User
GET  {{ baseURL }}/fetch-me
Authorization: Bearer {{ Authorization }}

###
# Get User By Id
GET {{ baseURL }}/user/204
Content-Type: application/json

###
# User Verify OTP
POST {{ baseURL }}/user/verify-otp
Content-Type: application/json

{
    "phoneNumber": "+84327476381",
	"code": "4925"
}

###
# User Resend OTP
POST {{ baseURL }}/user/resend-otp
Content-Type: application/json

{
    "phoneNumber": "0327476381",
}

###
# User forgot password
POST {{ baseURL }}/user/forgot-password
Content-Type: application/json

{
    "phoneNumber": "0327476381",
}

###
# User change password
POST {{ baseURL }}/user/change-password
Content-Type: application/json

{
    "phoneNumber": "0327476381",
    "password": "123456",
}

###
# User change password
PUT {{ baseURL }}/user/204
Content-Type: application/json
Authorization: Bearer {{ Authorization }}

{
    "name": "Pha"
}

###
# User change password
DELETE  {{ baseURL }}/user/204
Content-Type: application/json

{
    "phoneNumber": "0327476381",
}